#!/bin/bash

# iCloud CLI Tool - Global Installation Script
# After running this script, 'icloud' command will be available globally

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$HOME/.local/bin"

echo "=========================================="
echo "  iCloud CLI - Global Installation"
echo "=========================================="

# Check Python version
PYTHON_CMD=""
if command -v python3 &> /dev/null; then
    PYTHON_CMD="python3"
elif [ -f /usr/bin/python3 ]; then
    PYTHON_CMD="/usr/bin/python3"
elif [ -f /usr/local/bin/python3 ]; then
    PYTHON_CMD="/usr/local/bin/python3"
else
    echo "Error: python3 is not installed. Please install Python 3.8 or higher."
    exit 1
fi

echo "Using Python: $PYTHON_CMD"

PYTHON_VERSION=$($PYTHON_CMD --version 2>&1 | cut -d' ' -f2 | cut -d'.' -f1,2)
REQUIRED_VERSION="3.8"

if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$PYTHON_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
    echo "Error: Python 3.8 or higher is required. Found: $PYTHON_VERSION"
    exit 1
fi

# Create virtual environment if it doesn't exist
cd "$SCRIPT_DIR"
if [ ! -d "venv" ]; then
    echo "Creating virtual environment..."
    $PYTHON_CMD -m venv venv
fi

# Activate virtual environment
echo "Activating virtual environment..."
. venv/bin/activate

# Upgrade pip
echo "Upgrading pip..."
pip install --upgrade pip -q

# Install dependencies
echo "Installing dependencies..."
pip install -r requirements.txt -q

# Install project in editable mode
echo "Installing icloud-cli package..."
pip install -e . -q

# Create ~/.local/bin if it doesn't exist
mkdir -p "$INSTALL_DIR"

# Create wrapper script
WRAPPER_SCRIPT="$INSTALL_DIR/icloud"
echo "Creating wrapper script at $WRAPPER_SCRIPT..."

cat > "$WRAPPER_SCRIPT" << EOF
#!/bin/bash
# iCloud CLI wrapper script
# Auto-generated by install.sh

ICLOUD_HOME="$SCRIPT_DIR"
source "\$ICLOUD_HOME/venv/bin/activate"
exec icloud "\$@"
EOF

chmod +x "$WRAPPER_SCRIPT"

# Check if ~/.local/bin is in PATH
if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    echo ""
    echo "=========================================="
    echo "  IMPORTANT: Add to PATH"
    echo "=========================================="
    echo ""
    echo "~/.local/bin is not in your PATH."
    echo "Add the following line to your ~/.bashrc or ~/.zshrc:"
    echo ""
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo ""
    echo "Then run: source ~/.bashrc  (or source ~/.zshrc)"
    echo ""
    
    # Try to add to shell config automatically
    SHELL_RC=""
    if [ -f "$HOME/.zshrc" ]; then
        SHELL_RC="$HOME/.zshrc"
    elif [ -f "$HOME/.bashrc" ]; then
        SHELL_RC="$HOME/.bashrc"
    fi
    
    if [ -n "$SHELL_RC" ]; then
        read -p "Add to $SHELL_RC automatically? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            if ! grep -q 'export PATH="$HOME/.local/bin:$PATH"' "$SHELL_RC"; then
                echo '' >> "$SHELL_RC"
                echo '# iCloud CLI' >> "$SHELL_RC"
                echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$SHELL_RC"
                echo "Added to $SHELL_RC"
                echo "Run: source $SHELL_RC"
            else
                echo "PATH already configured in $SHELL_RC"
            fi
        fi
    fi
else
    echo ""
    echo "~/.local/bin is already in your PATH."
fi

echo ""
echo "=========================================="
echo "  Installation Complete!"
echo "=========================================="
echo ""
echo "Usage:"
echo "  icloud login -u your@icloud.com   # Login to iCloud"
echo "  icloud sync -f Documents          # Sync files"
echo "  icloud --help                     # Show help"
echo ""
